### ISSUE TITLE
Prioritize the cameras that will be shown 

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#119]
Based on the criteria decided on https://github.com/montevideo-tech/hybrid-meetup-platform/issues/118 implement the prioritization system to show each camera

**Comment by fpyoung** [comment]
This issue will be solved then the following issues are solved:
- https://github.com/montevideo-tech/hybrid-meetup-platform/issues/142
- https://github.com/montevideo-tech/hybrid-meetup-platform/issues/140
- https://github.com/montevideo-tech/hybrid-meetup-platform/issues/143
- https://github.com/montevideo-tech/hybrid-meetup-platform/issues/144 (not mandatory for now)

**Comment by marcovidonis** [comment]
I would imagine recently spoken would have higher priority, as they might also be likely to speak again soon, if they need to add something.
I think that we can solve both issues by defining something like priority weights (see my comment in #118), and we'll have greater flexibility in tweaking things in the future, if needed.
