### ISSUE TITLE
Implement a way to display the cameras considering the screen size(rows and columns).

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#130]
Right now there is a limit of cameras that can be displayed on a call, but what isn't solved is the way they will be displayed.
- Find the optimum number of cameras that can be displayed according to the screen size(xs,xl,etc) and implement it.
-  Find if there's a way to limit columns and if so the optimum number of rows according to the screensize and implement it.
- Remove scroll.

Acceptance Criteria:
- For every screen size(xs,sm,l, xl, etc) all the cameras that are displayed fit on the screen.
- The scroll was deleted.

**Comment by marcovidonis** [comment]
Also keep in mind that video tiles don't need to have a fixed size: we can make them a bit smaller on smaller viewports. Some platforms like Google Meet crop the video in a square, which could also be an option.
