### ISSUE TITLE
Solve linter issue

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#131]
On our local machines we aren't checking the linter cheks so we are able to create pull requests that failed due to this issue.
We need to find a way to make lint checks locally.

**Comment by marcovidonis** [comment]
If you use VSCode, it should highlight linting errors and give suggestions out of the box. In other text editors, you might need to install an add-on for it.

I remember some people in the team had issues initially because of conflicts with some global configs, so perhaps you can talk to @ghbogarin and @clararfe :)

**Comment by ghbogarin** [comment]
We did! In my case, I had both Prettier and ESLint extensions installed in VSCode. Disabling the Prettier extension did the trick for me. 

Also, here's my settings.json file for ESLint in case you find it useful: 
```
{
  "javascript.updateImportsOnFileMove.enabled": "always",
  "workbench.editorAssociations": {
    "*.pdf": "default"
  },
  "grunt.autoDetect": "on",
  "editor.codeActionsOnSave": {},
  "eslint.codeActionsOnSave.rules": null,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "prettier.singleQuote": true,
  "editor.formatOnSave": true,
  "window.zoomLevel": 2,
  "eslint.execArgv": null
}
```

**Comment by fpyoung** [comment]
Hey guys, we found a solution for this, basically the problem was that when you clone a repo git automatically uses for the entire project the linebreaks of the operating system you are using and since linter was checking if we had unix linebreaks there was a problem there.
What we decided is to remove the linebreak check on eslint, since it doesn't matter the linebreak you have once you pull the changes git automatically will assign you the linebreaks of your OS.

**Comment by marcovidonis** [comment]
Ok. There's a command or a setting in VSCode for the line brake too, I can't remember what it is but I had the same problem initially, until I ran that command :)
