### ISSUE TITLE
Implement new stylings based on the new approved mockups

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#137]
Implement in the stylings https://github.com/montevideo-tech/hybrid-meetup-platform/issues/132

**Comment by marcovidonis** [comment]
@fyoungqualabs @Unnil can you share the mockups here?

It would be good if this kind of discussions could be held in GitHub so more people have a chance to be part of the decision making, since this is a community project 🙂

**Comment by fpyoung** [comment]
Ciao Marco! totally agree, once we have the mockups we'll send them here so the community can have a voice in this decision.

**Comment by marcovidonis** [comment]
Thanks Felipe, I appreciate!
