### ISSUE TITLE
Change the name of the platform in multiple places

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#141]
![Image](https://user-images.githubusercontent.com/121059628/228016361-bae02fd8-6e84-4b56-ac2b-a91ffb0f1145.png)
Change the tab title to Hybridly.

![Image](https://user-images.githubusercontent.com/121059628/228017161-1dfa41ab-05fb-49f2-b1f1-7a56018ef932.png)
Change the header title to Hybridly

**Comment by fpyoung** [comment]
@marcovidonis we wanted to change the name of the platform bc we thought it was too long: Hybrid meetup Platform.
So we asked ChatGPT for possible names and one that came up is Hybridly. 
Do you like the name? Please say yes 😆

**Comment by marcovidonis** [comment]
YES! We definitely need a proper name! 😁

Hybridly sounds catchy, it's growing on me :) Yes, let's go with that if everyone's on board!

**Comment by marcovidonis** [comment]
Should we close this issue @JonaQuaLabs ?
