### ISSUE TITLE
SUBTASK: Implement a priority queue for rendering the remoteParticipants

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#142]
Create a priority queue to store the remoteParticipants information.
We are probably gonna need some way to show all the participants ordered by priority to render them.

**Comment by fpyoung** [comment]
We were investigatin with @JonaQuaLabs  and we discovered an external library called priorityQueue that might work. https://www.npmjs.com/package/js-priority-queue
@marcovidonis  Any thoughts about this? 
Of course this ticket needs further investigation before doing anything.

**Comment by marcovidonis** [comment]
priorityQueue looks good! Then we should be able to easily implement (and update, if necessary) the `comparator` function to our needs, comparing `priority` fields inside `participant` objects, for example.

**Comment by fpyoung** [comment]
okay so I tried to implement a priority queue and I come up with the following problem: 
If I store all the participants in a priorityQueue and one participants changes his status-let's say he starts speaking- the priority queue order is going to still be the same so I will need a way to modify the priority of that particular remoteParticipant.
So turns out for fixing this I have 2 choices: 
- Rebuild the priorityQueue O(n)
- Search for the element in the priority queue, remove it and insert it back again. There's no point on doing this since in the priority queue we are supposed to only have access to the top priority item. In other words, a nasty solution.

As a result of this I decided to use an AVL tree, so when this happens, let's say a participant starts speaking I will remove him from the AVL tree and insert him back again in O(log(n)).

I'll be using avl npm library.

@marcovidonis what do you think about this solution?

**Comment by marcovidonis** [comment]
I'm not familiar with AVL trees, but reading a bit about how they work and looking at the npm library (I assume it's [this one](https://www.npmjs.com/package/avl)?) it looks like a nice solution.

I see you set the status to "in progress": I suggest we always link the branch with the issue it solves, and open a draft PR while the work is in progress, so others can see what's being worked on and how. This way, the issue get closed automatically when the branch is merged. Thanks!

**Comment by fpyoung** [comment]
hey Marco, yes that's the library I was planning to use.
Regarding the issues and PRs that's my bad, I was doing that and then I totally forgot about it. From now on I'll link all the issues to their corresponding PRs.

**Comment by fpyoung** [comment]
@marcovidonis I tried to implement the remoteParticipantsAVL and turns out it adds a lot of complexity.
I found 2 ways of implementing this: 
Number 1: Instead of using the Map structure use an AVL structure, the problem with this every time we want to search for a remoteParticipant(and this happens all the time since every time we listen to an event we look for the guy who triggered that) we need to do this in a slower way(O(log(n)) compared to the Map that searchs on O(1). On the other hand the operations we do like 'increasing priority' require other operations(remove from the AVL an insert it back again) that add complexity to the code.
Number 2: Maintain the Map and the AVL, which adds way more complexity since we need to maintain both structures.

After analizying this I came up to the conclusion that is better to keep things the way they are: a list of remoteParticipants.
With this list I can implement a comparator function and sort the list using that when it gets rendered, in this way is very easy to add or remove conditions and it doesn't have a massive impact on the rest of the code.
```
 // To add a new criteria to the comparator you need to
  // Decide if it's higher or lower pririoty compared to the already established
  // if it's higher you must add the 'if' before otherwise add it after.
  const comparator = (participant1, participant2) => {
    if (participant1.speaking > participant2.speaking) {
      return -1;
    }

    return 1;
  };
```
In this way we will be able to prioritize the participants the way we wanted and keep working on this. 
I understand that this is not the most efficient solution and if this becomes a problem over time we can revisit this issue, but so far this is a solution that keeps us moving forward towards our goal. 
Any thoughts?

**Comment by marcovidonis** [comment]
Yeah as I said, I'm not very familiar with AVL trees and other structures, that's why I went for a simple map :) There might be more efficient solutions we could look into later, but I have a feeling that all the rendering operations React does, where we create new arrays at every state change etc, are probably more than we can save by changing the way we handle `remoteParticipants`!
