### ISSUE TITLE
Analyze Cost and Feasibility of Changing Backend Stack

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#157]
We need to analyze the cost and feasibility of changing our backend stack, with a focus on exploring alternatives to Supabase. This analysis should include the technical costs associated with making a transition, as well as the potential benefits. If changing the backend is determined to be a good option, we should also consider a progressive migration strategy, such as the one suggested by Nico during the Grooming session: keeping one part of the backend in Supabase and the other in Node, and gradually migrating to Node with each sprint. The findings of this analysis will be consulted with Nico Levy before making a final decision.

Acceptance Criteria:

- Research and evaluate if Supabase is still a good alternative
- Research and evaluate alternatives to Supabase
- Analyze the costs and benefits of changing the backend stack
- Assess the feasibility of implementing a progressive migration strategy
- 
Consult with @nicolevy to discuss the results and make a final decision

**Comment by fpyoung** [comment]
Keep in mind that this issue needs to be fixed after we decide what to do with the roles #156

**Comment by marcovidonis** [comment]
Are there any specific drawbacks that made you consider the idea of replacing the Back-End? Supabase definitely had some learning curve at the beginning, but it seems to me that it's been working fine, providing authentication, a database with real-time updates, and edge functions.

Is there anything in particular you think is missing? I'm just aware that replacing the Back-End, and especially all the edge function logic, would be quite a large job.

**Comment by fpyoung** [comment]
@marcovidonis hey Marco I sent you an email related to how we plan to move on these days and the deadlines we have.
Due to our deadline in end of april to host a Montevideo meetup we had a conversation with @nicolaslevy and we decided that we are going to stay with Supabase even though we are going to have high coupling with the platform.
