### ISSUE TITLE
Simulate 80 Participants on a Hybridly Call with Different Videos

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#160]
The goal of this task is to develop a method for simulating a Hybridly call with 80 participants concurrently, each with a different video. This will help us test the performance and stability of our platform under high load conditions and identify any potential bottlenecks or areas for optimization.

1. Develop a simulation strategy to create 80 concurrent participants on a Hybridly call
2. Ensure each participant has a different video stream
3. Monitor the performance and stability of the platform during the simulation
4. Identify any potential bottlenecks or areas for optimization

**Comment by JonaQuaLabs** [comment]
Hey @marcovidonis! have you ever had to implement something like this?. Any suggestion on the approach I can take ?

**Comment by marcovidonis** [comment]
Hey @JonaQuaLabs, I've never done anything like this unfortunately! Perhaps [this talk about testing video](https://youtu.be/ZPj8mWmE5fI) might help?
