### ISSUE TITLE
Ability to block all guests from unmuting themselves during calls

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#184]
As an admin, I want to have the ability to block all guests from unmuting themselves during calls. I want this feature to be available only to admins.
Admins and presenters will still be able to unmute themselves as needed.

- As an admin, I should be able to access the feature to block all guests from unmuting themselves during calls.
- The feature should only block guests from unmuting themselves, while still allowing admins and presenters to unmute themselves.
- The feature should be accessible thorugh one button in the control panel of the call(see image).

![Image](https://user-images.githubusercontent.com/121059628/232484464-0aaff628-3809-40de-a060-b921decc990f.png)

**Comment by fpyoung** [comment]
Comment during planning: Use the database to keep track on who can unmute themselves.

**Comment by juanpqualabs** [comment]
which icon should be used for this functionality?
should it be purple too?

**Comment by fpyoung** [comment]
good question, I would suggest adding something like this and in purple.

![Image](https://github.com/montevideo-tech/hybrid-meetup-platform/assets/121059628/5e841391-b58d-4183-9f26-844c639294a5)

But I'm open to suggestions

**Comment by juanpqualabs** [comment]
What do you think of this one?

![Image](https://github.com/montevideo-tech/hybrid-meetup-platform/assets/86672825/6cf73b74-b3d2-4082-95d1-b2e8c8dd1f07)

**Comment by fpyoung** [comment]
go for it with that one!
