### ISSUE TITLE
Block a specific guest from unmuting himself on the call

### ISSUE THREAD

**Issue by fpyoung** [montevideo-tech/hybrid-meetup-platform#185]
As an admin, I want to be able to block a specific guest from unmuting himself during the call. This feature should be implemented to prevent unwanted noise or interruptions from the guest during the call.
The feature should be displayed as a button next to the name of the participant and the quick out button. The guest will not be able to unmute himself on the call, and the unmute/mute button will be blocked on his screen.
This feature should not affect the ability of other participants to mute and unmute themselves on the call. All other participants should be able to mute and unmute themselves as usual.

Acceptance criteria

- A new button should be added next to the name of the participant and the quick out button that allows the moderator to block a specific guest from unmuting himself.
- The blocked guest should not be able to unmute himself on the call, and the unmute/mute button should be blocked on his screen.
- All other participants should be able to mute and unmute themselves as usual.

**Comment by juanpqualabs** [comment]
the ticket does not specify if once I block a participant from unmuting, I can re-enable him/her to unmute, is this expected for this ticket?

**Comment by fpyoung** [comment]
nice catch! I totally forgot about this.
Yes, this is expected from this ticket, you should be able to block someone from speaking but also be able to unblock him/her from doing that.
