### ISSUE TITLE
Implement Basic Chat Functionality

### ISSUE THREAD

**Issue by yulianag-qualabs** [montevideo-tech/hybrid-meetup-platform#201]
Description: As a user, I want to be able to send messages and see them in the Room, so that I can communicate with other users.

Acceptance Criteria:

A chat box is added to the Room interface.
Users can type messages in the chat box and send them.
Messages sent by users are displayed in the chat box in real-time.
Users can see all messages in the chat box, including messages sent by themselves and other users.

**Comment by yulianag-qualabs** [comment]
Based on #158

**Comment by yulianag-qualabs** [comment]
A new database was created in Supabase called "message-chat", which includes columns such as "providerId" (a foreign key from the "rooms" table that refers to the room ID), "email" (a foreign key from the "users-data" table), and "content" (the information typed by the user in the chat). The "message-chat" table is responsible for storing all the messages from all the rooms.

A file called "chat.js" was created in the "utils" folder to handle the chat messages. The "subscribeToNewMessages" function listens to new INSERTS made in the "message-chat" database. Meanwhile, the "onSendMessage" function inserts the message into the "message-chat" database.

The "Chat.jsx" component is responsible for rendering the chat. The "fetchMessages" function retrieves information from the database and sets the "messages" variable with the fetched messages.

**Comment by fpyoung** [comment]
astonishing
![Image](https://user-images.githubusercontent.com/121059628/234355198-1706c6f6-bb9f-4b23-848a-11438de6814b.png)
