### ISSUE TITLE
Create main layout on the UI with navigation

### ISSUE THREAD

**Issue by ghbogarin** [montevideo-tech/hybrid-meetup-platform#26]
Create the container for the list of rooms and other stuff that will come up. This should be a basic layout of the webpage.

Initial mockups: https://github.com/orgs/montevideo-tech/projects/2/views/1?pane=issue&itemId=19402993

**Comment by marcovidonis** [comment]
I would say this is more a workflow than it is a layout... @montevideo-tech/summer-camp-2023 anyone good with design that would like to create a wireframe for the app?

**Comment by ghbogarin** [comment]
Hey @marcovidonis , I added the wrong link in the description. I've just updated the link to the one with the initial mockups.  My idea with this ticket was to create a very basic layout to start plugging the basic components for the app (authentication, room) with basic navigation using react router. We'd probably drop it in future iterations.

I'll create a draft asap for this but if anyone is up to design better wireframes, that'd be great!
