### ISSUE TITLE
Create player wrapper for the UI

### ISSUE THREAD

**Issue by ghbogarin** [montevideo-tech/hybrid-meetup-platform#31]

**Comment by marcovidonis** [comment]
There's already a wrapper for the `<video>` element, which I made in #22. Does this issue include controls to mute the video and audio too?

@montevideo-tech/summer-camp-2023

**Comment by mpollingerQualabs** [comment]
@marcovidonis i'd say that if the controls to mute/unmute and enable/disable camera are not part of #4 and #5 (or #39), then add those controls on this one.
