### ISSUE TITLE
Build the first iteration of the Room View

### ISSUE THREAD

**Issue by nreyes-qualabs** [montevideo-tech/hybrid-meetup-platform#38]
The idea here is to build a very basic first attempt at a room view. This won't include actual video players. For now it'll just contain the divs that will eventually wrap the players that transmit each participant's camera and some buttons. The main focus of this first attempt will be to make sure that these divs adjust position and size depending on the amount of people present in the room. 

Since people can't join rooms yet, this view will include a button to increase the amount of video placeholders by one, so that the view can be manually tested.

**Comment by mpollingerQualabs** [comment]
I'd recommend using `grid` for the CSS layout of the room.

**Comment by marcovidonis** [comment]
Unfortunately MUI doesn't provide CSS Grid out of the box, so it was easier to just use the `Grid` component they provide, which is based on flex box.

I think this issue is already being closed by the current state of #39.
