### ISSUE TITLE
Implement Room View

### ISSUE THREAD

**Issue by nreyes-qualabs** [montevideo-tech/hybrid-meetup-platform#53]
The `/rooms/{{room_id}}` view.

**Comment by nreyes-qualabs** [comment]
Currently working on making the view intialize and use our Room object as it should. For now it'll continue to ignore the url's roomId and use a JWT from .env until we have that connection solved.

**Comment by nreyes-qualabs** [comment]
- [x] connect to Room
- [x] connect to proper Room (the one with id given by URL)
- [x] fix grid bugs for rowLimit > 2
- [x] move user camera to fixed position bottom right
- [x] make video components fit grid item
- [ ]  ~~make it so that it's not so terribly ugly~~

**Comment by nreyes-qualabs** [comment]
ready to be merged . PR: https://github.com/montevideo-tech/hybrid-meetup-platform/pull/39

**Comment by mpollingerQualabs** [comment]
Would issue #3 get closed when closing this tickets?
