### ISSUE TITLE
Add autogenerated user id into users data table

### ISSUE THREAD

**Issue by clararfe** [montevideo-tech/hybrid-meetup-platform#67]

**Comment by marcovidonis** [comment]
This might or might not be useful... anyway, once you're signed in, this is how you get user data in the front end. I used it to add the user ID to the rooms table.

https://github.com/montevideo-tech/hybrid-meetup-platform/blob/27-create-and-list-rooms-ui/frontend/src/views/Rooms.jsx#L32-35
