### ISSUE TITLE
FE: Fix store managment

### ISSUE THREAD

**Issue by clararfe** [montevideo-tech/hybrid-meetup-platform#90]
We need to have saved on the storage the user data: email, token, role

**Comment by ghbogarin** [comment]
Hey @marcovidonis! Just wanted to mention, Redux doesn't use localstore but I think we could use redux-persist for this goal

**Comment by marcovidonis** [comment]
Hi @ghbogarin! Thanks, I started looking at the redux-toolkit docs and I think they mention the module also provides persistency... but I haven't yet got the the point where they say how :) Do you have experience with that?

**Comment by ghbogarin** [comment]
Just opened a PR for this issue! https://github.com/montevideo-tech/hybrid-meetup-platform/pull/106

**Comment by fpyoung** [comment]
hey @ghbogarin @marcovidonis we tested this in dev and it seems to be working so if you guys confirm I'll remove this issue.

**Comment by ghbogarin** [comment]
@fyoungqualabs it is! This issue is outdated, you can safely close it :D
